[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "dotnet restore CarAutomotive.sln",
  "dotnet publish CarAutomotive.API/CarAutomotive.API.csproj -c Release -o out"
]

[start]
cmd = "ASPNETCORE_URLS=http://0.0.0.0:$PORT ./out/CarAutomotive.API"